### Delete a specific persons entry
DELETE http://localhost:3001/api/persons/1
Content-Type: application/json

###

### Get all entries after deletion
GET http://localhost:3001/api/persons

### Add a new phonebook entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name" : "Kartik",
  "number": "040-123456"
}

###

### Add a entry with missing fields
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "040-123456"
}


###

### Add a entry with existing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas", 
  "number": "040-123456"
}